name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate ASCII Artwork
              run: |
               cowsay -f dragon "Hello World!!!" >> dragon.txt
               sudo apt install cowsay
               cat dragon.txt
