name: Multi Job Workflow

on: 
  schedule:
    - cron: '*/10 * * * *'

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt install cowsay

            - name: Generate Artwork
              run: cowsay -f dragon "Hello World!!!" >> dragon.txt

            - name: Upload Artwork
              uses: actions/upload-artifact@v3
              with:
                name: dragon
                path: dragon.txt
            
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: Download Artwork
              uses: actions/download-artifact@v3
              with:
                name: dragon

            - name: List files
              run: ls -la

            - name: Test that file exists
              run: grep -i "world" dragon.txt


    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
            - name: Download Artwork
              uses: actions/download-artifact@v3
              with:
                name: dragon

            - name: Output Artwork
              run: cat dragon.txt

